### ISSUE TITLE
use vfork() instead of fork()

### ISSUE THREAD

**Issue by alex-tee** [atsushieno/aria2web#12]
Hi, I noticed this uses fork() (through tiny-process-library) and thought I'd let you know about this:
https://github.com/surge-synthesizer/surge/issues/657#issuecomment-466800504

It's not recommended to use fork() for plugins

**Comment by atsushieno** [comment]
Ohh, I hadn't thought about that. Yeah child processes (especially with the simplified utility library I make use of) would definitely involve fork() and that'd be problematic. Thanks, that issue is going to be an infinite but fun reading.

Since it is called as part of the dependency I would have to fork and rewrite [that part](https://gitlab.com/eidheim/tiny-process-library/-/blob/master/process_unix.cpp#L56). I will work on my spare time.

Let me shoot a quick question though; was there any useful tool to detect problematic plugin behavior that lets you find this issue?

**Comment by alex-tee** [comment]
awesome!

> was there any useful tool to detect problematic plugin behavior that lets you find this issue?

There's [lv2lint](https://open-music-kontrollers.ch/lv2/lv2lint/) that detects a bunch of problems but I'm not sure if it also detects use of fork().

**Comment by atsushieno** [comment]
Ah, I thought you used some tool to find the issue. Maybe it was just caught by your debugger I guess then. Thanks for the hint anyways!

**Comment by atsushieno** [comment]
I have made a dirty hack to locally patch tiny-process-library instead of creating a fork for this vfork thing. 0255c8b contains a patching step in `build.sh`.

The resulting binary seems to load on zrythm and qtractor, but (1) I have trouble on enabling jackd on my Ubuntu 20.04 laptop so any DAWs that requires jackd can verify only UI part, and (2) zrythm on `develop` branch somehow goes into infinite crash report dialog loop with or without this fix. The stack trace is [here](https://gist.github.com/atsushieno/3007862cd0d27b7708f27929ddac5919). Maybe it is debuggable locally, but that's going to be another investigation.

Anyhow I'm closing this issue now. Thanks for the report!

**Comment by alex-tee** [comment]
:+1: thanks for the stack trace, will fix it soon. I made some internal changes and there's many regressions at the moment

**Comment by atsushieno** [comment]
Oh you had an idea even from that log? That's cool. Let me know if you would like further details on it :)

**Comment by alex-tee** [comment]
yes those are very helpful! please submit them whenever they pop up (no registration needed) :slightly_smiling_face:
